// Tickers with no working logo from Massive or Finnhub as of the last
// scripts/seed-logos.mjs run, and not already covered by a hand-curated
// WIKI_LOGOS entry in logos.ts either. Generated by scripts/seed-logos.mjs —
// do not hand-edit.
//
// To close a gap: find a source logo (Wikimedia Commons search "<company>
// logo", first File: result, resolve via the imageinfo API — see WIKI_LOGOS'
// own header comment in logos.ts for the exact method already used for 8
// other tickers) and add it to WIKI_LOGOS. The ticker drops off this list
// automatically the next time this script runs.
export const MISSING_LOGOS: string[] = [
  "XYZ100",
  "SP500",
  "NIFTY",
  "JP225",
  "KR200",
  "IBOV",
  "MAGS",
  "SMH",
  "SOXL",
  "XBI",
  "XLE",
  "URNM",
  "EWJ",
  "EWT",
  "EWY",
  "EWZ",
  "KORU",
];
